name: build
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited, deleted]
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10
      - uses: actions/checkout@v4
      - name: Generate README
        uses: bxb100/issueblog@astro-paper
        with:
          blog_author: "John Bi"
          md_header: |
            ## GitLog
            My personal blog using issues and GitHub Actions [RSS Feed](https://bxb100.github.io/rss.xml)
          blog_image_url: https://cdn.jsdelivr.net/gh/bxb100/bxb100@master/png2.png
          blog_url: https://bxb100.github.io

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Build
        # we need formatter the generate markdown file
        run: |
          pnpm run format
          pnpm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./dist"
      - name: Summary
        run: echo "Ready to deploy :rocket:" >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
