name: 'Generate Blog'
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, labeled, unlabeled]
  issue_comment:
    types: [created, edited]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
      - uses: actions/checkout@v2
      - name: Generate README
        uses: bxb100/issueblog@hexo
        with:
          blog_author: "John Bi"
          md_header: |
              ## GitLog
              My personal blog using issues and GitHub Actions [RSS Feed](https://bxb100.github.io/blog/feed.xml)
          blog_image_url: https://cdn.jsdelivr.net/gh/bxb100/bxb100@master/png2.png
          blog_url: https://bxb100.github.io
